<?php

/**
 * @file
 * Contains icecat.module..
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_presave().
 */
function icecat_entity_presave(EntityInterface $entity) {
  /** @var \Drupal\icecat\Controller\IcecatController $icecatController */
  $icecatController = \Drupal::service('icecat.mapper');
  $icecatController->setEntity($entity);
  $icecatController->mapEntityData();
}
