icecat.icecat_mapping.*:
  type: config_entity
  label: 'Icecat mapping'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    entity_type:
      type: text
      label: 'Entity type'
    entity_type_bundle:
      type: text
      label: 'Entity type bundle'
    data_input_field:
      type: text
      label: 'The field to use as data source'

icecat.icecat_mapping_link.*:
  type: config_entity
  label: 'Icecat mapping link'
  mapping:
    id:
      type: string
      label: 'ID'
    mapping:
      type: text
      label: 'Mapping reference'
    local_field:
      type: text
      label: 'Local field'
    remote_field_type:
      type: text
      label: 'Remote field type'
    remote_field:
      type: text
      label: 'Remote field'
